name: appedu
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  dio: ^5.7.0
  intl: ^0.18.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter_lints: ^3.0.1
  get_storage: ^2.1.1
  shared_preferences: ^2.1.1
  jwt_decoder: ^2.0.1
  get: ^4.6.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/p.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/p.png

